apiVersion: v1
kind: Pod
metadata:
  labels:
    app: agente-claudio-zamora
spec:
  serviceAccountName: jenkins
    containers:
    - name: node-tool
      image: node:24-alpine
      command: ['cat']
      tty: true
    - name: buildkit
      image: moby/buildkit:latest
      command: ['sleep']
      args: ['99d']
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-config-dockerhub
          mountPath: /docker-config/dockerhub
          readOnly: true
        - name: docker-config-github
          mountPath: /docker-config/github
          readOnly: true
    - name: kubectl-tool
      image: alpine/k8s:1.30.4
      command: ['sleep']
      args: ['99d']
  volumes:
    - name: docker-config-dockerhub
      secret:
        secretName: dockerhub-config
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: docker-config-github
      secret:
        secretName: ghcr-config
        items:
          - key: .dockerconfigjson
            path: config.json
