apiVersion: v1
kind: Namespace
metadata:
  name: ns-claudio-zamora
  labels:
    app: claudio-zamora
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-claudio-zamora
  namespace: ns-claudio-zamora
data:
  AMBIENTE: "develop"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-claudio-zamora
  namespace: ns-claudio-zamora
type: Opaque
stringData:
  API_KEY: "pgpassword-app" # Valor de ejemplo para el laboratorio.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-claudio-zamora
  namespace: ns-claudio-zamora
  labels:
    app: claudio-zamora
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claudio-zamora
  template:
    metadata:
      labels:
        app: claudio-zamora
    spec:
      containers:
        - name: claudio-zamora
          image: mi-app-node:latest
          imagePullPolicy: Never
          env:
            - name: AMBIENTE
              valueFrom:
                configMapKeyRef:
                  name: config-claudio-zamora
                  key: AMBIENTE
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-claudio-zamora
                  key: API_KEY
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: svc-claudio-zamora
  namespace: ns-claudio-zamora
  labels:
    app: claudio-zamora
spec:
  selector:
    app: claudio-zamora
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: claudio-zamora
  namespace: ns-claudio-zamora
  labels:
    app: claudio-zamora
spec:
  ingressClassName: nginx
  rules:
    - host: laboratorio3.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: svc-claudio-zamora
                port:
                  number: 80
